name: event_bus
version: 0.4.0
author: Marco Jakob <majakob@gmx.ch>
description: A simple Event Bus using Dart Streams for decoupling applications
homepage: http://code.makery.ch/library/dart-event-bus
documentation: http://www.dartdocs.org/documentation/event_bus/latest/
dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  logging: '>=0.10.0 <0.11.0'
  unittest: '>=0.11.0 <0.12.0'
